[package]
name = "git-store"
version = "0.0.1"
authors = ["Christoph Burgdorf <christoph.burgdorf@bvsn.org>"]

[dependencies]
clap = "*"
uuid = "*"

[dependencies.rustc-serialize]
git = "https://github.com/andersk/rustc-serialize.git"
branch = "io-error"
